receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"  # 👈 fix applied

exporters:
  otlp:
    endpoint: tempo:4317  # or another trace backend
  debug:
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:9464"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
