global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'application-service'
    metrics_path: /prometheus
    static_configs:
      - targets: ['application:8000']
  - job_name: 'recommendation-service'
    metrics_path: /prometheus
    static_configs:
      - targets: [ 'recommendation:8001' ]
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464']
